ONIT.VismaNet/Models/CustomDto/DescriptiveDto.cs, ONIT.VismaNet/Models/CustomerInvoice.cs, ONIT.VismaNet/ONIT.VismaNet.nuspec
Removes default CreditTerm and PaymentMethod on CustomerInvoice
=> Remove customerinvoice defaults

ONIT.VismaNet/Lib/Data/BaseCrudDataClass.cs, ONIT.VismaNet/Lib/DtoProviderBase.cs, ONIT.VismaNet/Lib/VismaNetApiHelper.cs, ONIT.VismaNet/Models/Shipment.cs, ONIT.VismaNet/Models/ShipmentDetailLine.cs, ONIT.VismaNet/Models/ShipmentOrderLine.cs
=> Fixed issue in Put<T> + automated update of lines in entities

ONIT.VismaNet/Lib/VismaNetApiHelper.cs, ONIT.VismaNet/Lib/VismaNetControllers.cs, ONIT.VismaNet/Lib/VismaNetWebClient.cs, ONIT.VismaNet/VismaNet.cs
New requirements from Visma - contact Visma in order to obtain client id and secret.
=> Implemented new token resource

ONIT.VismaNet/Models/CustomerInvoice.cs
Default values on customer invoice is causing confusion/errors.
=> Removed default values on CustomerInvoice

ONIT.VismaNet/Lib/Data/BaseCrudDataClass.cs, ONIT.VismaNet/Lib/VismaNetWebClient.cs, ONIT.VismaNet/Models/CashSale.cs, ONIT.VismaNet/Models/Contact.cs, ONIT.VismaNet/Models/Customer.cs, ONIT.VismaNet/Models/Employee.cs, ONIT.VismaNet/Models/Helpers/IHaveInternalId.cs, ONIT.VismaNet/Models/Helpers/IHaveNumber.cs, ONIT.VismaNet/Models/Helpers/IProvideIdentificator.cs, ONIT.VismaNet/Models/Inventory.cs, ONIT.VismaNet/Models/InvoiceBase.cs, ONIT.VismaNet/Models/JournalTransaction.cs, ONIT.VismaNet/Models/Project.cs, ONIT.VismaNet/Models/Shipment.cs, ONIT.VismaNet/Models/Supplier.cs, ONIT.VismaNet/Models/SupplierInvoice.cs, ONIT.VismaNet/ONIT.VismaNet.csproj, ONIT.VismaNet/packages.config
- Removed unnecessary fields from dto types
- Made HttpClient static internally, as according to https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.sendasync(v=vs.110).aspx. This will reduce socket usage under heavy load.
=> Redone the identificator and made httpClient static

ONIT.VismaNet/Models/InvoiceBase.cs
=> Added exchangeRate to invoices

ONIT.VismaNet/Models/Supplier.cs
=> Make supplierClass on Supplier writable

ONIT.VismaNet/Lib/VismaNetWebClient.cs, ONIT.VismaNet/Models/Helpers/VismaNetAuthorization.cs, ONIT.VismaNet/VismaNet.cs
Set branchId in the VismaNet constructor.
```csharp
var vismaNet = new VismaNet(123456, "74a1535e-ec65-474d-9076-30917de92296", 20);
```
=> Added branch to constructor. Closes #39

ONIT.VismaNet/Lib/Data/BranchData.cs, ONIT.VismaNet/Lib/VismaNetControllers.cs, ONIT.VismaNet/Models/Branch.cs, ONIT.VismaNet/Models/CustomDto/IdName.cs, ONIT.VismaNet/Models/CustomerDocument.cs, ONIT.VismaNet/ONIT.VismaNet.csproj, ONIT.VismaNet/VismaNet.cs
=> Aztherion master

ONIT.VismaNet/Exceptions/VismaNetExceptionHandler.cs
Else we will never get the exception details from Visma.net only Nullreference Exception
=> Checking if details.ExceptionMessage != null 

Visma.net/Models/Dimensions/DimensionSegment.cs, Visma.net/Models/Dimensions/DimensionSegmentValue.cs, Visma.net/Models/Subaccount.cs, Visma.net/VismaNet.cs, Visma.net/lib/DAta/SubaccountData.cs, Visma.net/lib/VismaNetApiHelper.cs, Visma.net/lib/VismaNetControllers.cs
Added subaccount, and toDto on put on dimensions, and fix for creating dimensions
=> Added subaccount, and som fixes on dimensions

Visma.net.sln, Visma.net.tests/CustomerTest.cs, Visma.net.tests/EntityBaseTest.cs, Visma.net.tests/InventoryTests.cs, Visma.net.tests/Properties/AssemblyInfo.cs, Visma.net.tests/Visma.net.tests.csproj, Visma.net.tests/VismaNetTestHelpers.cs, Visma.net.tests/app.config, Visma.net.tests/packages.config, Visma.net/Models/Attachment.cs, Visma.net/Models/CustomDto/Address.cs, Visma.net/Models/CustomDto/Attributes.cs, Visma.net/Models/CustomDto/ContactInfo.cs, Visma.net/Models/CustomDto/Country.cs, Visma.net/Models/CustomDto/CustomerAttributes.cs, Visma.net/Models/CustomDto/DescriptiveDto.cs, Visma.net/Models/CustomDto/LocationSummary.cs, Visma.net/Models/CustomDto/WarehouseDetails.cs, Visma.net/Models/Customer.cs, Visma.net/Models/DirectDebitLine.cs, Visma.net/Models/Inventory.cs, Visma.net/lib/VismaNetWebClient.cs, appveyor.yml
This is the way to go forward with implementing new endpoints and data models. This way we'll have control if/when we break something and/or if something does not work as anticipated.
=>  Created test stucture and implemented tests for Inventory and Customer 

Visma.net/Models/InvoiceBase.cs
… to keep consistency between CustomerInvoice and CreditNote
=> Changed to using CustomerSummary class on customer on InvoiceBase... 

Visma.net/Models/CustomerInvoice.cs
Added the missing property CustomerVatZone on the object CustomerInvoice.
=> Added CustomerVatZone on CustomerInvoice

Visma.net/Models/CustomerVatZone.cs
Added an implicit constructor to the customerVatZone object
=> Added an implicit constructor to the customerVatZone object

Visma.net/Models/InvoiceBase.cs
Added missing properties to credit note
- BranchNumber
- Note
- CustomerVatZone
=> Added the following properties to CreditNote:

Visma.net/Models/SalesOrder.cs
Added "inBaseCurrency" properties and "exchangeRate" property to SalesOrder
=> "inBaseCurrency" and "exchangeRate" added to SalesOrder

Visma.net/lib/DAta/InventoryData.cs
Added possibility to filter Inventory based on availabilityLastModifiedDateTime.
=> Added Inventory.GetAllAvailabilityUpdatedSince()

Visma.net/lib/DAta/SalesOrderData.cs, Visma.net/lib/ShipmentActionResult.cs, Visma.net/lib/VismaNetApiHelper.cs
This is needed by SalesOrder/CreateShipment method.
=> Added support for CreateShipmentActionResultDto.

Visma.net/Visma.net.csproj, Visma.net/VismaNet.cs, Visma.net/lib/DAta/CustomerDocumentData.cs, Visma.net/lib/DAta/CustomerInvoiceData.cs, Visma.net/lib/VismaNetControllers.cs, Visma.net/lib/VismaNetWebClient.cs
changed add large method to use new optimized V2 of customerinvoice.
=> Fix for retryhandler + added paging to customerinvoice

Visma.net/Lib/Data/PurchaseOrderData.cs, Visma.net/Models/CustomDto/PurchaseOrderLineAccount.cs, Visma.net/Models/PurchaseOrder.cs, Visma.net/Models/PurchaseOrderLine.cs, Visma.net/VismaNet.cs, Visma.net/lib/VismaNetControllers.cs
The endpoint PurchaseOrder has been added to the library.
=> Endpoint PurchaseOrder added

Visma.net/Models/Employee.cs, Visma.net/Models/PurchaseOrder.cs
Added missing properties to Employee and PurchaseOrder
=> Added missing properties

Visma.net/Models/CashTransaction.cs, Visma.net/Models/CashTransactionDetails.cs, Visma.net/Models/CashTransactionTaxDetails.cs, Visma.net/Models/CustomDto/DescriptiveDto.cs, Visma.net/Models/Enums/TaxCalulationModes.cs, Visma.net/VismaNet.cs, Visma.net/lib/DAta/CashSaleData.cs, Visma.net/lib/DAta/CashTransactionData.cs, Visma.net/lib/VismaNetControllers.cs
Added Cashtransaction endpoint ,ScreenID CA304000
=> CashTransaction endpoint added

Visma.net/Models/CustomDto/DescriptiveDto.cs, Visma.net/Models/Inventory.cs
added defaultwarehouse ,defaultIssueFrom and defaultReceiptTo
=> inventory warehouselocation

Visma.net/Models/CustomerCreditNote.cs
**Added properties:**
1. contact
2. project
3. invoiceAddress
4. invoiceContact
5. sendToautoInvoice
6. origInvoiceDate
7. financialPeriod
8. cashAccount
**Moved properties to their respective region**
1. customer
2. branchNumber
3. amountInCurrency (private set)
4. note
5. customerVatZone
**Removed properties**
1. vatcode (Is a propery on the customerInvoiceLine)
=> Added and modified properties on CustomerCreditNote

Visma.net/lib/DAta/CustomerInvoiceData.cs
The ForCustomer method uses the wrong URL, result is a JSON Parse exception
=> ForCustomer in CustomerData wrong url

Visma.net/lib/VismaNetApiHelper.cs
Changed endpoint for AddAttachmentToCreditNote method
=> Endpoint for AddAttachmentToCreditNote method

Visma.net/Models/Project.cs, Visma.net/lib/DAta/ProjectData.cs
- 'Project' class to DtoPaginatedProviderBase it now has the metadata property
- They fixed the misspelling of 'projectManager'
=> Visma project PaginatedCrud

Visma.net/Models/Supplier.cs, Visma.net/Models/SupplierInvoice.cs
Added missing properties to supplier model
- overrideNumberSeries
- note
=> Added missing properties to supplier model

Visma.net.Tests/LocationTests.cs, Visma.net.Tests/Snapshots/LocationTests.CanDeserializeToDto.verified.txt, Visma.net.Tests/Snapshots/LocationTests.CanDeserializeToEntity.verified.txt, Visma.net.Tests/Visma.net.Tests.csproj, Visma.net/Models/Location.cs, Visma.net/Visma.net.csproj, Visma.net/lib/Data/LocationData.cs
added entity.InternalPrepareForUpdate(); in locationData and disabled ignorprop in location model.
=> fix location create and update

Visma.net/Models/ProjectTransaction.cs, Visma.net/Models/ProjectTransactionLine.cs, Visma.net/VismaNet.cs, Visma.net/lib/Data/ProjectTransactionData.cs, Visma.net/lib/VismaNetControllers.cs
Created the project transaction endpoint
=> Project transaction
